<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="juck.libs.api" Version="1.0.0" />
    <PackageReference Include="juck.libs.auth" Version="1.0.0" />
    <PackageReference Include="MongoDB.Bson" Version="3.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Expenses.Domain\Expenses.Domain.csproj" />
  </ItemGroup>

</Project>
