name: Pipeline - CI

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and build .NET
        uses: andrejuck/reusable-workflows/.github/actions/step-dotnet-build@main
        with:
          working-dir: code
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          unit-tests-csproj: Expenses.Tests/Expenses.Tests.csproj