name: Pipeline - CI

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #OpenSSL1.1 dependency must use ubuntu 20.04, latest versions use the following step
      - name: Install OpenSSL 1.1 compatibility
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1 || true

      - name: Setup and build .NET
        uses: andrejuck/reusable-workflows/.github/actions/step-dotnet-build@main
        with:
          working-dir: code
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          unit-tests-csproj: Expenses.Tests/Expenses.Tests.csproj